module.exports = {
    JsSandboxCommand: require('./js-sandbox-command'),
    GcCommand: require('./gc-command'),
    MemoryUsageCommand: require('./memory-usage-command'),
    SayCommand: require('./say-command'),
    UnknownCommand: require('./unknown-command'),
    ReactCommand: require('./react-command'),
    ReactStrCommand: require('./react-str-command'),
    ServersCommand: require('./servers-command'),
    SubscribeCommand: require('./subscribe-command'),
    UnsubscribeCommand: require('./unsubscribe-command'),
    ColorCommand: require('./color-command'),
    PinCommand: require('./pin-command'),
    UnpinCommand: require('./unpin-command'),
    EmojiUsageStatsCommand: require('./emoji-usage-stats-command'),
    SaveCustomCommand: require('./save-custom-comand'),
    RemoveCustomCommand: require('./remove-custom-command'),
    CommandListCommand: require('./command-list-command'),
    CustomCommand: require('./custom-command')
};
